SIM:
  SIMULATOR: isaac_gym
  RENDER: False
  GRAVITY: (0.0, 0.0, -9.8)
  USE_DEFAULT_STEP_PARAMS: True
  INIT_VIEWER_CAMERA_POSITION: (+3.1375, -2.6327, +2.8679)
  INIT_VIEWER_CAMERA_TARGET: (0, 0, 0)
  SIM_DEVICE: cuda:0
  GRAPHICS_DEVICE_ID: 0
  USE_GPU_PIPELINE: True
